version: '3'
services:
  backend:
    image: python:3.11.6
    volumes:
      - .:/app
    working_dir: /app
    command: bash -c "pip3 install -r requirements.txt && python3 api.py"
    ports:
      - 3000:3000

  frontend:
    image: node:22
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    ports:
      - 4000:4000